# DO NOT EDIT THIS FILE!
#
# Python module INF1822.NamingService generated by omniidl

import omniORB
omniORB.updateModule("INF1822.NamingService")

# ** 1. Stub files contributing to this module
import inf1822_idl

# ** 2. Sub-modules

# ** 3. End
