# DO NOT EDIT THIS FILE!
#
# Python module INF1822 generated by omniidl

import omniORB
omniORB.updateModule("INF1822")

# ** 1. Stub files contributing to this module
import inf1822_idl

# ** 2. Sub-modules
import NamingService

# ** 3. End
