module INF1822 {
	interface Device {
		attribute unsigned long id;
		attribute string type;
	};

	interface LightDevice: Device {
		attribute long lightLevel;
	};

	interface MasterLightDevice: LightDevice {
		void startMonitoringDevice(inout LightDevice device);
	};

	// Possible types for device (incomplete).
	enum ObjectType {
		MasterLightDeviceType,
		LightDeviceType
	};
};

module NamingService {
	// A list of IORs.
	typedef sequence<string> IORList;

	interface ObjectManager {
		// Usado por um objeto para se registrar junto ao serviço.
		// Pode retornar false caso algum erro tenha ocorrido.
		boolean register(in string ior, in string name, in string type);

		// Usado por um objeto para se desregistrar junto ao serviço.
		// Pode retornar false caso algum erro tenha ocorrido.
		boolean deregister(in string ior, in string name);

		// Retorna o IOR de um objeto dado seu nome.
		// Pode retornar um erro caso o objeto não exista.
		string getByName(in string name);

		// Retorna uma lista de IORs de objetos registrados pertencentes
		// ao tipo passado. Pode retornar uma lista vazia.
		IORList getByType(in string type);

		// Retorna o IOR de um objeto que é o "master" de seu tipo. 
		// Pode retornar um erro caso o objeto não exista.
		string getMasterForType(in string type);
	};
};
