module INF1822 {
	interface Device {
		attribute unsigned long id;
		attribute string type;
	};

	interface LightDevice: Device {
		attribute long lightLevel;
	};

	interface MasterLightDevice: LightDevice {
		void startMonitoringDevice(inout LightDevice device);
	};
};