# DO NOT EDIT THIS FILE!
#
# Python module NamingService generated by omniidl

import omniORB
omniORB.updateModule("NamingService")

# ** 1. Stub files contributing to this module
import inf1822_idl

# ** 2. Sub-modules

# ** 3. End
